// frontend_vue/src/views/Home.vue
<template>
  <div class="home text-center">
    <div class="jumbotron">
      <h1 class="display-3">Auth-Api</h1>
      <p class="lead">Learning Auth and Vue</p>
      <hr class="my-4">
      <p>Register for content</p>
      <p class="lead">
        <router-link
         class="btn btn-primary btn-lg"
         :to="{ name:'Signup' }"
         role="button">Sign Up</router-link>
      </p>
    </div>
  </div>
</template>

<script>

</script>

// frontend_react/src/views/Home.js
import React from 'react';
import { Link } from 'react-router-dom';

export default function Home(){
    return (
        <div className="jumbotron text-center container-md mt-5">
            <h1 className="display-3">Sign Up!</h1>
            <p className="lead">This is a test page, to learn more, sign up!</p>
            <hr className="my-4" />
            <p>Made by Igor Becker</p>
            <p className="lead">
            <Link 
                className="btn btn-primary btn-md"
                to="/signup"
                role="button"
            >SignUp</Link>
            </p>
        </div>
    );
}
